### ISSUE TITLE
Rubber band selection does not work correctly when panning_mode is true

### ISSUE THREAD

**Issue by Kmayankkr** [orensbruli/QNetworkxGraph#34]

**Comment by orensbruli** [comment]
Thank you. It makes sense. What do you think we could do? We can disable rubber band selection when in panning mode. Or maybe we could do rubber band only when a key is pressed (probably this solution is much difficult). On the other side, I think in Photoshop for panning the spacebar have to be pressed and a hand appears on the screen and the you can pan. What's your opinion?

**Comment by orensbruli** [comment]
Maybe something like this?
https://www.youtube.com/watch?v=t3xSCaqZqho

**Comment by Kmayankkr** [comment]
Fixed via PR #35

**Comment by orensbruli** [comment]
How?

**Comment by Kmayankkr** [comment]
Initially - setDragMode to RubberBandMode
While left + right click is held - setDragMode to ScrollHandDrag
When released - setDragMode back to RubberBandMode
(The bug was caused because DragMode was being set to NoDrag when mouse button was released)
